package me.moru3.survivalbingo

import org.bukkit.Bukkit
import org.bukkit.Material
import org.bukkit.command.Command
import org.bukkit.command.CommandSender
import org.bukkit.entity.Player
import org.bukkit.inventory.ItemStack
import org.bukkit.inventory.meta.MapMeta
import org.bukkit.plugin.java.JavaPlugin
import java.awt.image.BufferedImage
import javax.imageio.ImageIO


class SurvivalBingo : JavaPlugin() {
    private val card: BufferedImage = ImageIO.read(this.getResource("images/bingo_card_1.png"))
    private val language = Config(this, "languages.yml")
    val items = mutableMapOf<Material, BufferedImage>()
    val check: BufferedImage = ImageIO.read(this.getResource("images/status/bingo_hole_2.png"))
    override fun onEnable() {
        language.saveDefaultConfig()
        items.apply {
            put(Material.ACACIA_BOAT, ImageIO.read(this@SurvivalBingo.getResource("images/items/acacia_boat.png")))
            put(Material.ACACIA_DOOR, ImageIO.read(this@SurvivalBingo.getResource("images/items/acacia_door.png")))
            put(Material.ACACIA_SIGN, ImageIO.read(this@SurvivalBingo.getResource("images/items/acacia_sign.png")))
            put(Material.APPLE, ImageIO.read(this@SurvivalBingo.getResource("images/items/apple.png")))
            put(Material.ARMOR_STAND, ImageIO.read(this@SurvivalBingo.getResource("images/items/armor_stand.png")))
            put(Material.ARROW, ImageIO.read(this@SurvivalBingo.getResource("images/items/arrow.png")))
            put(Material.BAKED_POTATO, ImageIO.read(this@SurvivalBingo.getResource("images/items/baked_potato.png")))
            put(Material.BAMBOO, ImageIO.read(this@SurvivalBingo.getResource("images/items/bamboo.png")))
            put(Material.BEEF, ImageIO.read(this@SurvivalBingo.getResource("images/items/beef.png")))
            put(Material.BEETROOT, ImageIO.read(this@SurvivalBingo.getResource("images/items/beetroot.png")))
            put(Material.BEETROOT_SEEDS, ImageIO.read(this@SurvivalBingo.getResource("images/items/beetroot_seeds.png")))
            put(Material.BEETROOT_SOUP, ImageIO.read(this@SurvivalBingo.getResource("images/items/beetroot_soup.png")))
            put(Material.BELL, ImageIO.read(this@SurvivalBingo.getResource("images/items/bell.png")))
            put(Material.BIRCH_BOAT, ImageIO.read(this@SurvivalBingo.getResource("images/items/birch_boat.png")))
            put(Material.BIRCH_DOOR, ImageIO.read(this@SurvivalBingo.getResource("images/items/birch_door.png")))
            put(Material.BIRCH_SIGN, ImageIO.read(this@SurvivalBingo.getResource("images/items/birch_sign.png")))
            put(Material.BLACK_DYE, ImageIO.read(this@SurvivalBingo.getResource("images/items/black_dye.png")))
            put(Material.BLUE_DYE, ImageIO.read(this@SurvivalBingo.getResource("images/items/blue_dye.png")))
            put(Material.BONE, ImageIO.read(this@SurvivalBingo.getResource("images/items/bone.png")))
            put(Material.BONE_MEAL, ImageIO.read(this@SurvivalBingo.getResource("images/items/bone_meal.png")))
            put(Material.BOOK, ImageIO.read(this@SurvivalBingo.getResource("images/items/book.png")))
            put(Material.BOW, ImageIO.read(this@SurvivalBingo.getResource("images/items/bow.png")))
            put(Material.BOWL, ImageIO.read(this@SurvivalBingo.getResource("images/items/bowl.png")))
            put(Material.BREAD, ImageIO.read(this@SurvivalBingo.getResource("images/items/bread.png")))
            put(Material.BREWING_STAND, ImageIO.read(this@SurvivalBingo.getResource("images/items/brewing_stand.png")))
            put(Material.BRICK, ImageIO.read(this@SurvivalBingo.getResource("images/items/brick.png")))
            put(Material.BROWN_DYE, ImageIO.read(this@SurvivalBingo.getResource("images/items/brown_dye.png")))
            put(Material.BUCKET, ImageIO.read(this@SurvivalBingo.getResource("images/items/bucket.png")))
            put(Material.CAKE, ImageIO.read(this@SurvivalBingo.getResource("images/items/cake.png")))
            put(Material.CAMPFIRE, ImageIO.read(this@SurvivalBingo.getResource("images/items/campfire.png")))
            put(Material.CARROT, ImageIO.read(this@SurvivalBingo.getResource("images/items/carrot.png")))
            put(Material.CARROT_ON_A_STICK, ImageIO.read(this@SurvivalBingo.getResource("images/items/carrot_on_a_stick.png")))
            put(Material.CAULDRON, ImageIO.read(this@SurvivalBingo.getResource("images/items/cauldron.png")))
            put(Material.CHARCOAL, ImageIO.read(this@SurvivalBingo.getResource("images/items/charcoal.png")))
            put(Material.CHICKEN, ImageIO.read(this@SurvivalBingo.getResource("images/items/chicken.png")))
            put(Material.CLAY_BALL, ImageIO.read(this@SurvivalBingo.getResource("images/items/clay_ball.png")))
            put(Material.CLOCK, ImageIO.read(this@SurvivalBingo.getResource("images/items/clock.png")))
            put(Material.COAL, ImageIO.read(this@SurvivalBingo.getResource("images/items/coal.png")))
            put(Material.COCOA_BEANS, ImageIO.read(this@SurvivalBingo.getResource("images/items/cocoa_beans.png")))
            put(Material.COD, ImageIO.read(this@SurvivalBingo.getResource("images/items/cod.png")))
            put(Material.COD_BUCKET, ImageIO.read(this@SurvivalBingo.getResource("images/items/cod_bucket.png")))
            put(Material.COMPARATOR, ImageIO.read(this@SurvivalBingo.getResource("images/items/comparator.png")))
            put(Material.COMPASS, ImageIO.read(this@SurvivalBingo.getResource("images/items/compass.png")))
            put(Material.COOKED_BEEF, ImageIO.read(this@SurvivalBingo.getResource("images/items/cooked_beef.png")))
            put(Material.COOKED_CHICKEN, ImageIO.read(this@SurvivalBingo.getResource("images/items/cooked_chicken.png")))
            put(Material.COOKED_COD, ImageIO.read(this@SurvivalBingo.getResource("images/items/cooked_cod.png")))
            put(Material.COOKED_MUTTON, ImageIO.read(this@SurvivalBingo.getResource("images/items/cooked_mutton.png")))
            put(Material.COOKED_PORKCHOP, ImageIO.read(this@SurvivalBingo.getResource("images/items/cooked_porkchop.png")))
            put(Material.COOKED_RABBIT, ImageIO.read(this@SurvivalBingo.getResource("images/items/cooked_rabbit.png")))
            put(Material.COOKED_SALMON, ImageIO.read(this@SurvivalBingo.getResource("images/items/cooked_salmon.png")))
            put(Material.COOKIE, ImageIO.read(this@SurvivalBingo.getResource("images/items/cookie.png")))
            put(Material.CYAN_DYE, ImageIO.read(this@SurvivalBingo.getResource("images/items/cyan_dye.png")))
            put(Material.DARK_OAK_BOAT, ImageIO.read(this@SurvivalBingo.getResource("images/items/dark_oak_boat.png")))
            put(Material.DARK_OAK_DOOR, ImageIO.read(this@SurvivalBingo.getResource("images/items/dark_oak_door.png")))
            put(Material.DARK_OAK_SIGN, ImageIO.read(this@SurvivalBingo.getResource("images/items/dark_oak_sign.png")))
            put(Material.DIAMOND, ImageIO.read(this@SurvivalBingo.getResource("images/items/diamond.png")))
            put(Material.DRIED_KELP, ImageIO.read(this@SurvivalBingo.getResource("images/items/dried_kelp.png")))
            put(Material.EGG, ImageIO.read(this@SurvivalBingo.getResource("images/items/egg.png")))
            put(Material.EMERALD, ImageIO.read(this@SurvivalBingo.getResource("images/items/emerald.png")))
            put(Material.ENDER_PEARL, ImageIO.read(this@SurvivalBingo.getResource("images/items/ender_pearl.png")))
            put(Material.FEATHER, ImageIO.read(this@SurvivalBingo.getResource("images/items/feather.png")))
            put(Material.FERMENTED_SPIDER_EYE, ImageIO.read(this@SurvivalBingo.getResource("images/items/fermented_spider_eye.png")))
            put(Material.FISHING_ROD, ImageIO.read(this@SurvivalBingo.getResource("images/items/fishing_rod.png")))
            put(Material.FLINT, ImageIO.read(this@SurvivalBingo.getResource("images/items/flint.png")))
            put(Material.FLINT_AND_STEEL, ImageIO.read(this@SurvivalBingo.getResource("images/items/flint_and_steel.png")))
            put(Material.FLOWER_POT, ImageIO.read(this@SurvivalBingo.getResource("images/items/flower_pot.png")))
            put(Material.FURNACE_MINECART, ImageIO.read(this@SurvivalBingo.getResource("images/items/furnace_minecart.png")))
            put(Material.GHAST_TEAR, ImageIO.read(this@SurvivalBingo.getResource("images/items/ghast_tear.png")))
            put(Material.GLASS_BOTTLE, ImageIO.read(this@SurvivalBingo.getResource("images/items/glass_bottle.png")))
            put(Material.GLISTERING_MELON_SLICE, ImageIO.read(this@SurvivalBingo.getResource("images/items/glistering_melon_slice.png")))
            put(Material.GLOWSTONE_DUST, ImageIO.read(this@SurvivalBingo.getResource("images/items/glowstone_dust.png")))
            put(Material.GOLDEN_APPLE, ImageIO.read(this@SurvivalBingo.getResource("images/items/golden_apple.png")))
            put(Material.GOLDEN_AXE, ImageIO.read(this@SurvivalBingo.getResource("images/items/golden_axe.png")))
            put(Material.GOLDEN_BOOTS, ImageIO.read(this@SurvivalBingo.getResource("images/items/golden_boots.png")))
            put(Material.GOLDEN_CARROT, ImageIO.read(this@SurvivalBingo.getResource("images/items/golden_carrot.png")))
            put(Material.GOLDEN_CHESTPLATE, ImageIO.read(this@SurvivalBingo.getResource("images/items/golden_chestplate.png")))
            put(Material.GOLDEN_HELMET, ImageIO.read(this@SurvivalBingo.getResource("images/items/golden_helmet.png")))
            put(Material.GOLDEN_HOE, ImageIO.read(this@SurvivalBingo.getResource("images/items/golden_hoe.png")))
            put(Material.GOLDEN_HORSE_ARMOR, ImageIO.read(this@SurvivalBingo.getResource("images/items/golden_horse_armor.png")))
            put(Material.GOLD_INGOT, ImageIO.read(this@SurvivalBingo.getResource("images/items/gold_ingot.png")))
            put(Material.GOLD_NUGGET, ImageIO.read(this@SurvivalBingo.getResource("images/items/gold_nugget.png")))
            put(Material.GRAY_DYE, ImageIO.read(this@SurvivalBingo.getResource("images/items/gray_dye.png")))
            put(Material.GREEN_DYE, ImageIO.read(this@SurvivalBingo.getResource("images/items/green_dye.png")))
            put(Material.GUNPOWDER, ImageIO.read(this@SurvivalBingo.getResource("images/items/gunpowder.png")))
            put(Material.HOPPER, ImageIO.read(this@SurvivalBingo.getResource("images/items/hopper.png")))
            put(Material.HOPPER_MINECART, ImageIO.read(this@SurvivalBingo.getResource("images/items/hopper_minecart.png")))
            put(Material.INK_SAC, ImageIO.read(this@SurvivalBingo.getResource("images/items/ink_sac.png")))
            put(Material.IRON_AXE, ImageIO.read(this@SurvivalBingo.getResource("images/items/iron_axe.png")))
            put(Material.IRON_BOOTS, ImageIO.read(this@SurvivalBingo.getResource("images/items/iron_boots.png")))
            put(Material.IRON_CHESTPLATE, ImageIO.read(this@SurvivalBingo.getResource("images/items/iron_chestplate.png")))
            put(Material.IRON_DOOR, ImageIO.read(this@SurvivalBingo.getResource("images/items/iron_door.png")))
            put(Material.IRON_HELMET, ImageIO.read(this@SurvivalBingo.getResource("images/items/iron_helmet.png")))
            put(Material.IRON_HOE, ImageIO.read(this@SurvivalBingo.getResource("images/items/iron_hoe.png")))
            put(Material.IRON_HORSE_ARMOR, ImageIO.read(this@SurvivalBingo.getResource("images/items/iron_horse_armor.png")))
            put(Material.IRON_INGOT, ImageIO.read(this@SurvivalBingo.getResource("images/items/iron_ingot.png")))
            put(Material.IRON_LEGGINGS, ImageIO.read(this@SurvivalBingo.getResource("images/items/iron_leggings.png")))
            put(Material.IRON_NUGGET, ImageIO.read(this@SurvivalBingo.getResource("images/items/iron_nugget.png")))
            put(Material.ITEM_FRAME, ImageIO.read(this@SurvivalBingo.getResource("images/items/item_frame.png")))
            put(Material.JUNGLE_BOAT, ImageIO.read(this@SurvivalBingo.getResource("images/items/jungle_boat.png")))
            put(Material.JUNGLE_DOOR, ImageIO.read(this@SurvivalBingo.getResource("images/items/jungle_door.png")))
            put(Material.JUNGLE_SIGN, ImageIO.read(this@SurvivalBingo.getResource("images/items/jungle_sign.png")))
            put(Material.KELP, ImageIO.read(this@SurvivalBingo.getResource("images/items/kelp.png")))
            put(Material.KNOWLEDGE_BOOK, ImageIO.read(this@SurvivalBingo.getResource("images/items/knowledge_book.png")))
            put(Material.LANTERN, ImageIO.read(this@SurvivalBingo.getResource("images/items/lantern.png")))
            put(Material.LAPIS_LAZULI, ImageIO.read(this@SurvivalBingo.getResource("images/items/lapis_lazuli.png")))
            put(Material.LAVA_BUCKET, ImageIO.read(this@SurvivalBingo.getResource("images/items/lava_bucket.png")))
            put(Material.LEAD, ImageIO.read(this@SurvivalBingo.getResource("images/items/lead.png")))
            put(Material.LEATHER, ImageIO.read(this@SurvivalBingo.getResource("images/items/leather.png")))
            put(Material.LIGHT_BLUE_DYE, ImageIO.read(this@SurvivalBingo.getResource("images/items/light_blue_dye.png")))
            put(Material.LIGHT_GRAY_DYE, ImageIO.read(this@SurvivalBingo.getResource("images/items/light_gray_dye.png")))
            put(Material.LIME_DYE, ImageIO.read(this@SurvivalBingo.getResource("images/items/lime_dye.png")))
            put(Material.MAGENTA_DYE, ImageIO.read(this@SurvivalBingo.getResource("images/items/magenta_dye.png")))
            put(Material.MAGMA_CREAM, ImageIO.read(this@SurvivalBingo.getResource("images/items/magma_cream.png")))
            put(Material.MELON_SEEDS, ImageIO.read(this@SurvivalBingo.getResource("images/items/melon_seeds.png")))
            put(Material.MELON_SLICE, ImageIO.read(this@SurvivalBingo.getResource("images/items/melon_slice.png")))
            put(Material.MILK_BUCKET, ImageIO.read(this@SurvivalBingo.getResource("images/items/milk_bucket.png")))
            put(Material.MINECART, ImageIO.read(this@SurvivalBingo.getResource("images/items/minecart.png")))
            put(Material.MUTTON, ImageIO.read(this@SurvivalBingo.getResource("images/items/mutton.png")))
            put(Material.NAME_TAG, ImageIO.read(this@SurvivalBingo.getResource("images/items/name_tag.png")))
            put(Material.OAK_BOAT, ImageIO.read(this@SurvivalBingo.getResource("images/items/oak_boat.png")))
            put(Material.OAK_DOOR, ImageIO.read(this@SurvivalBingo.getResource("images/items/oak_door.png")))
            put(Material.OAK_SIGN, ImageIO.read(this@SurvivalBingo.getResource("images/items/oak_sign.png")))
            put(Material.ORANGE_DYE, ImageIO.read(this@SurvivalBingo.getResource("images/items/orange_dye.png")))
            put(Material.PAINTING, ImageIO.read(this@SurvivalBingo.getResource("images/items/painting.png")))
            put(Material.PAPER, ImageIO.read(this@SurvivalBingo.getResource("images/items/paper.png")))
            put(Material.PHANTOM_MEMBRANE, ImageIO.read(this@SurvivalBingo.getResource("images/items/phantom_membrane.png")))
            put(Material.PINK_DYE, ImageIO.read(this@SurvivalBingo.getResource("images/items/pink_dye.png")))
            put(Material.POISONOUS_POTATO, ImageIO.read(this@SurvivalBingo.getResource("images/items/poisonous_potato.png")))
            put(Material.PORKCHOP, ImageIO.read(this@SurvivalBingo.getResource("images/items/porkchop.png")))
            put(Material.POTATO, ImageIO.read(this@SurvivalBingo.getResource("images/items/potato.png")))
            put(Material.PUFFERFISH, ImageIO.read(this@SurvivalBingo.getResource("images/items/pufferfish.png")))
            put(Material.PUFFERFISH_BUCKET, ImageIO.read(this@SurvivalBingo.getResource("images/items/pufferfish_bucket.png")))
            put(Material.PUMPKIN_PIE, ImageIO.read(this@SurvivalBingo.getResource("images/items/pumpkin_pie.png")))
            put(Material.PUMPKIN_SEEDS, ImageIO.read(this@SurvivalBingo.getResource("images/items/pumpkin_seeds.png")))
            put(Material.PURPLE_DYE, ImageIO.read(this@SurvivalBingo.getResource("images/items/purple_dye.png")))
            put(Material.QUARTZ, ImageIO.read(this@SurvivalBingo.getResource("images/items/quartz.png")))
            put(Material.RABBIT, ImageIO.read(this@SurvivalBingo.getResource("images/items/rabbit.png")))
            put(Material.RABBIT_FOOT, ImageIO.read(this@SurvivalBingo.getResource("images/items/rabbit_foot.png")))
            put(Material.RABBIT_HIDE, ImageIO.read(this@SurvivalBingo.getResource("images/items/rabbit_hide.png")))
            put(Material.RABBIT_STEW, ImageIO.read(this@SurvivalBingo.getResource("images/items/rabbit_stew.png")))
            put(Material.REDSTONE, ImageIO.read(this@SurvivalBingo.getResource("images/items/redstone.png")))
            put(Material.RED_DYE, ImageIO.read(this@SurvivalBingo.getResource("images/items/red_dye.png")))
            put(Material.REPEATER, ImageIO.read(this@SurvivalBingo.getResource("images/items/repeater.png")))
            put(Material.ROTTEN_FLESH, ImageIO.read(this@SurvivalBingo.getResource("images/items/rotten_flesh.png")))
            put(Material.SADDLE, ImageIO.read(this@SurvivalBingo.getResource("images/items/saddle.png")))
            put(Material.SALMON, ImageIO.read(this@SurvivalBingo.getResource("images/items/salmon.png")))
            put(Material.SALMON_BUCKET, ImageIO.read(this@SurvivalBingo.getResource("images/items/salmon_bucket.png")))
            put(Material.SCUTE, ImageIO.read(this@SurvivalBingo.getResource("images/items/scute.png")))
            put(Material.SHEARS, ImageIO.read(this@SurvivalBingo.getResource("images/items/shears.png")))
            put(Material.SLIME_BALL, ImageIO.read(this@SurvivalBingo.getResource("images/items/slime_ball.png")))
            put(Material.SNOWBALL, ImageIO.read(this@SurvivalBingo.getResource("images/items/snowball.png")))
            put(Material.SPIDER_EYE, ImageIO.read(this@SurvivalBingo.getResource("images/items/spider_eye.png")))
            put(Material.SPRUCE_BOAT, ImageIO.read(this@SurvivalBingo.getResource("images/items/spruce_boat.png")))
            put(Material.SPRUCE_DOOR, ImageIO.read(this@SurvivalBingo.getResource("images/items/spruce_door.png")))
            put(Material.SPRUCE_SIGN, ImageIO.read(this@SurvivalBingo.getResource("images/items/spruce_sign.png")))
            put(Material.STICK, ImageIO.read(this@SurvivalBingo.getResource("images/items/stick.png")))
            put(Material.STRING, ImageIO.read(this@SurvivalBingo.getResource("images/items/string.png")))
            put(Material.SUGAR, ImageIO.read(this@SurvivalBingo.getResource("images/items/sugar.png")))
            put(Material.SUGAR_CANE, ImageIO.read(this@SurvivalBingo.getResource("images/items/sugar_cane.png")))
            put(Material.SWEET_BERRIES, ImageIO.read(this@SurvivalBingo.getResource("images/items/sweet_berries.png")))
            put(Material.TNT_MINECART, ImageIO.read(this@SurvivalBingo.getResource("images/items/tnt_minecart.png")))
            put(Material.TROPICAL_FISH, ImageIO.read(this@SurvivalBingo.getResource("images/items/tropical_fish.png")))
            put(Material.TROPICAL_FISH_BUCKET, ImageIO.read(this@SurvivalBingo.getResource("images/items/tropical_fish_bucket.png")))
            put(Material.TURTLE_EGG, ImageIO.read(this@SurvivalBingo.getResource("images/items/turtle_egg.png")))
            put(Material.TURTLE_HELMET, ImageIO.read(this@SurvivalBingo.getResource("images/items/turtle_helmet.png")))
            put(Material.WATER_BUCKET, ImageIO.read(this@SurvivalBingo.getResource("images/items/water_bucket.png")))
            put(Material.WHEAT, ImageIO.read(this@SurvivalBingo.getResource("images/items/wheat.png")))
            put(Material.WHEAT_SEEDS, ImageIO.read(this@SurvivalBingo.getResource("images/items/wheat_seeds.png")))
            put(Material.WHITE_DYE, ImageIO.read(this@SurvivalBingo.getResource("images/items/white_dye.png")))
            put(Material.WOODEN_AXE, ImageIO.read(this@SurvivalBingo.getResource("images/items/wooden_axe.png")))
            put(Material.WRITTEN_BOOK, ImageIO.read(this@SurvivalBingo.getResource("images/items/written_book.png")))
            put(Material.YELLOW_DYE, ImageIO.read(this@SurvivalBingo.getResource("images/items/yellow_dye.png")))
            put(Material.ACTIVATOR_RAIL, ImageIO.read(this@SurvivalBingo.getResource("images/items/activator_rail.png")))
            put(Material.DETECTOR_RAIL, ImageIO.read(this@SurvivalBingo.getResource("images/items/detector_rail.png")))
            put(Material.POWERED_RAIL, ImageIO.read(this@SurvivalBingo.getResource("images/items/powered_rail.png")))
            put(Material.RAIL, ImageIO.read(this@SurvivalBingo.getResource("images/items/rail.png")))
            put(Material.ACACIA_SAPLING, ImageIO.read(this@SurvivalBingo.getResource("images/items/acacia_sapling.png")))
            put(Material.BIRCH_SAPLING, ImageIO.read(this@SurvivalBingo.getResource("images/items/birch_sapling.png")))
            put(Material.DARK_OAK_SAPLING, ImageIO.read(this@SurvivalBingo.getResource("images/items/dark_oak_sapling.png")))
            put(Material.JUNGLE_SAPLING, ImageIO.read(this@SurvivalBingo.getResource("images/items/jungle_sapling.png")))
            put(Material.OAK_SAPLING, ImageIO.read(this@SurvivalBingo.getResource("images/items/oak_sapling.png")))
            put(Material.SPRUCE_SAPLING, ImageIO.read(this@SurvivalBingo.getResource("images/items/spruce_sapling.png")))
        }
    }

    override fun onCommand(sender: CommandSender, command: Command, label: String, args: Array<out String>): Boolean {
        if(sender !is Player) {sender.sendMessage(language.getMessage("player_only_command"));return true}
        if(args.isEmpty()) {sender.sendMessage(language.getMessage("no_parameters"));return true}
        when(args[0]) {
            "test" -> {
                val item = ItemStack(Material.FILLED_MAP)
                val mapMeta = item.itemMeta as MapMeta
                mapMeta.apply {
                    mapView = Bukkit.createMap(sender.world).apply {
                        isUnlimitedTracking = false
                        addRenderer( RendererCard(Card(this@SurvivalBingo, card)) )
                    }
                }
                item.itemMeta = mapMeta
                sender.inventory.setItem(8, item)
            }
        }
        return true
    }
}